using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MyApp.SourceGeneration;

[Generator]
public sealed class PluginRegistrationGenerator : IIncrementalGenerator
{
    private static readonly ImmutableArray<PluginRegistration> PluginRegistrations =
    [
        new(
            "MyApp.Plugins.ICommandPlugin",
            "global::MyApp.Plugins.ICommandPlugin",
            "RegisterCommandPlugins",
            "CommandPluginRegistration.g.cs"),
        new(
            "MyApp.Plugins.IStartupPlugin",
            "global::MyApp.Plugins.IStartupPlugin",
            "RegisterStartupPlugins",
            "StartupPluginRegistration.g.cs")
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        foreach (var pluginRegistration in PluginRegistrations)
        {
            var registration = pluginRegistration;

            var pluginImplementations = context.SyntaxProvider
                .CreateSyntaxProvider(IsCandidate, (ctx, token) => GetPluginImplementation(ctx, token, registration))
                .Where(symbol => symbol is not null)
                .Select((symbol, _) => symbol!)
                .Collect();

            context.RegisterSourceOutput(
                pluginImplementations,
                (productionContext, symbols) => EmitRegistrationSource(productionContext, registration, symbols));
        }
    }

    private static bool IsCandidate(SyntaxNode node, CancellationToken _)
        => node is ClassDeclarationSyntax { BaseList: not null };

    private static INamedTypeSymbol? GetPluginImplementation(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken,
        PluginRegistration registration)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        if (classSymbol.IsAbstract)
        {
            return null;
        }

        var pluginInterface = context.SemanticModel.Compilation.GetTypeByMetadataName(registration.InterfaceMetadataName);
        if (pluginInterface is null)
        {
            return null;
        }

        foreach (var implementedInterface in classSymbol.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(implementedInterface, pluginInterface))
            {
                return classSymbol;
            }
        }

        return null;
    }

    private static void EmitRegistrationSource(
        SourceProductionContext context,
        PluginRegistration registration,
        ImmutableArray<INamedTypeSymbol> pluginTypes)
    {
        var uniquePlugins = pluginTypes.IsDefaultOrEmpty
            ? ImmutableArray<INamedTypeSymbol>.Empty
            : [
                ..pluginTypes
                    .Distinct(SymbolEqualityComparer.Default)
                    .OfType<INamedTypeSymbol>()
                    .OrderBy(static symbol => symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat), StringComparer.Ordinal)
            ];

        var source = GenerateSource(registration, uniquePlugins);
        context.AddSource(registration.HintName, source);
    }

    private static string GenerateSource(PluginRegistration registration, ImmutableArray<INamedTypeSymbol> plugins)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("namespace MyApp;");
        builder.AppendLine();
        builder.AppendLine("public static partial class ServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine($"    static partial void {registration.RegistrationMethodName}(IServiceCollection services)");
        builder.AppendLine("    {");

        foreach (var plugin in plugins)
        {
            var fullyQualifiedName = plugin.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.AppendLine(
                $"        services.AddSingleton<{registration.InterfaceTypeName}, {fullyQualifiedName}>();");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private sealed class PluginRegistration(
        string interfaceMetadataName,
        string interfaceTypeName,
        string registrationMethodName,
        string hintName)
    {
        public string InterfaceMetadataName { get; } = interfaceMetadataName;
        public string InterfaceTypeName { get; } = interfaceTypeName;
        public string RegistrationMethodName { get; } = registrationMethodName;
        public string HintName { get; } = hintName;
    }
}
